// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pod} from '../models';
import {main} from '../models';

export function CancelSubtask(arg1:string):Promise<string>;

export function ConfirmTask(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function CreateDirectTask(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function DeleteSession(arg1:string):Promise<string>;

export function DirectChat(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GetAgentDialogue(arg1:string):Promise<Array<pod.AgentDialogueJSON>>;

export function GetChatMessages(arg1:string):Promise<Array<pod.ChatMessageJSON>>;

export function GetConfirmationsForMaster(arg1:string):Promise<Array<main.TaskConfirmation>>;

export function GetLeaderPlan():Promise<Array<pod.AgentDialogueJSON>>;

export function GetMasterTasks():Promise<Array<pod.MasterTaskJSON>>;

export function GetSubtasks(arg1:string):Promise<Array<pod.SubtaskJSON>>;

export function GetSubtasksBySession(arg1:string):Promise<Array<pod.SubtaskJSON>>;

export function GetTaskConfirmation(arg1:string):Promise<main.TaskConfirmation>;

export function GetTeamChat(arg1:string):Promise<Array<main.TeamChatMessage>>;

export function GetWorkDir():Promise<string>;

export function ListAgents():Promise<Array<pod.AgentInfoJSON>>;

export function ListTeamDetails():Promise<Array<pod.TeamDetailJSON>>;

export function ListTeams():Promise<Array<string>>;

export function LoadSummonedItems():Promise<Array<pod.SummonedItemJSON>>;

export function OpenTerminal():Promise<string>;

export function PickFolder():Promise<string>;

export function RenameMasterTask(arg1:string,arg2:string):Promise<string>;

export function RunSubtask(arg1:string):Promise<string>;

export function SaveSummonedItems(arg1:Array<pod.SummonedItemJSON>):Promise<void>;

export function SendFeedback(arg1:string,arg2:string):Promise<string>;

export function SendTeamChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetWorkDir(arg1:string):Promise<string>;

export function StartExpertTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartWindowDrag():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
