// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dashboard} from '../models';

export function CancelMasterTask(arg1:string,arg2:string):Promise<string>;

export function CancelSubtask(arg1:string,arg2:string):Promise<string>;

export function DeleteMasterTask(arg1:string,arg2:string):Promise<string>;

export function GetAgentDialogue(arg1:string,arg2:string):Promise<Array<dashboard.AgentDialogueJSON>>;

export function GetLeaderFlowchart(arg1:string,arg2:string):Promise<string>;

export function GetLeaderPlan(arg1:string):Promise<Array<dashboard.AgentDialogueJSON>>;

export function GetLogContent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLogFiles(arg1:string,arg2:string):Promise<Array<dashboard.LogFileJSON>>;

export function GetMasterTasks():Promise<Array<dashboard.MasterTaskJSON>>;

export function GetSubtasks(arg1:string,arg2:string):Promise<Array<dashboard.SubtaskJSON>>;

export function GetTasks(arg1:string):Promise<Array<dashboard.TaskJSON>>;

export function GetWorkspaces():Promise<Array<dashboard.WorkspaceJSON>>;

export function LogFrontend(arg1:string):Promise<void>;

export function RegisterWorkspace(arg1:string):Promise<string>;

export function ResumeMasterTask(arg1:string,arg2:string):Promise<string>;
