// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pod} from '../models';

export function CancelSubtask(arg1:string):Promise<string>;

export function GetAgentDialogue(arg1:string):Promise<Array<pod.AgentDialogueJSON>>;

export function GetChatMessages(arg1:string):Promise<Array<pod.ChatMessageJSON>>;

export function GetLeaderPlan():Promise<Array<pod.AgentDialogueJSON>>;

export function GetMasterTasks():Promise<Array<pod.MasterTaskJSON>>;

export function GetSubtasks(arg1:string):Promise<Array<pod.SubtaskJSON>>;

export function GetWorkDir():Promise<string>;

export function ListTeams():Promise<Array<string>>;

export function OpenTerminal():Promise<string>;

export function RunSubtask(arg1:string):Promise<string>;

export function SendFeedback(arg1:string,arg2:string):Promise<string>;

export function SetWorkDir(arg1:string):Promise<string>;

export function StartTask(arg1:string,arg2:string):Promise<string>;

export function StartWindowDrag():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
