// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSubtask(arg1) {
  return window['go']['main']['App']['CancelSubtask'](arg1);
}

export function GetAgentDialogue(arg1) {
  return window['go']['main']['App']['GetAgentDialogue'](arg1);
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetLeaderPlan() {
  return window['go']['main']['App']['GetLeaderPlan']();
}

export function GetMasterTasks() {
  return window['go']['main']['App']['GetMasterTasks']();
}

export function GetSubtasks(arg1) {
  return window['go']['main']['App']['GetSubtasks'](arg1);
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function OpenTerminal() {
  return window['go']['main']['App']['OpenTerminal']();
}

export function RunSubtask(arg1) {
  return window['go']['main']['App']['RunSubtask'](arg1);
}

export function SendFeedback(arg1, arg2) {
  return window['go']['main']['App']['SendFeedback'](arg1, arg2);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}
