// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMasterTask(arg1, arg2) {
  return window['go']['main']['App']['CancelMasterTask'](arg1, arg2);
}

export function CancelSubtask(arg1, arg2) {
  return window['go']['main']['App']['CancelSubtask'](arg1, arg2);
}

export function DeleteMasterTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteMasterTask'](arg1, arg2);
}

export function GetAgentDialogue(arg1, arg2) {
  return window['go']['main']['App']['GetAgentDialogue'](arg1, arg2);
}

export function GetLeaderFlowchart(arg1, arg2) {
  return window['go']['main']['App']['GetLeaderFlowchart'](arg1, arg2);
}

export function GetLeaderPlan(arg1) {
  return window['go']['main']['App']['GetLeaderPlan'](arg1);
}

export function GetLogContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogContent'](arg1, arg2, arg3);
}

export function GetLogFiles(arg1, arg2) {
  return window['go']['main']['App']['GetLogFiles'](arg1, arg2);
}

export function GetMasterTasks() {
  return window['go']['main']['App']['GetMasterTasks']();
}

export function GetSubtasks(arg1, arg2) {
  return window['go']['main']['App']['GetSubtasks'](arg1, arg2);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function RegisterWorkspace(arg1) {
  return window['go']['main']['App']['RegisterWorkspace'](arg1);
}

export function ResumeMasterTask(arg1, arg2) {
  return window['go']['main']['App']['ResumeMasterTask'](arg1, arg2);
}
